GO
USE TECres
GO

CREATE TRIGGER No_Borrar_Ubi ON [dbo].[UBICACION] FOR DELETE
AS
DECLARE @p int 
SELECT @p=ID FROM deleted

IF (SELECT ID FROM deleted)<=472
BEGIN
 RAISERROR('NO SE PUEDE ELIMINAR AL SER UN VALOR DEFAULT',16,-1)
    ROLLBACK TRANSACTION
END
ELSE
	 DELETE FROM UBICACION
	 WHERE UBICACION.ID=@p


GO
CREATE TRIGGER No_Borrar_Admi ON [dbo].[ADMINISTRADOR] INSTEAD OF DELETE
AS
DECLARE @p int 
SELECT @p=Cedula FROM deleted

IF (SELECT Cedula FROM deleted)=123456789
BEGIN
 RAISERROR('NO SE PUEDE ELIMINAR AL SER UN VALOR DEFAULT',16,-1)
    ROLLBACK TRANSACTION
END
ELSE
	 DELETE FROM ADMINISTRADOR
	 WHERE ADMINISTRADOR.Cedula=@p

GO
CREATE TRIGGER No_Borrar_Perfil ON [dbo].[PERFIL_DE_CLIENTE] INSTEAD OF DELETE
AS
DECLARE @p VARCHAR(50)
SELECT @p=Nombre FROM deleted

IF (SELECT Nombre FROM deleted)='Agente' OR (SELECT Nombre FROM deleted)='Anunciante' OR  (SELECT Nombre FROM deleted)='Constructor' OR  (SELECT Nombre FROM deleted)='Propietario'
BEGIN
 RAISERROR('NO SE PUEDE ELIMINAR AL SER UN VALOR DEFAULT',16,-1)
    ROLLBACK TRANSACTION
END
ELSE
	 DELETE FROM PERFIL_DE_CLIENTE
	 WHERE PERFIL_DE_CLIENTE.Nombre=@p

GO
CREATE TRIGGER No_Borrar_Ocupacion ON [dbo].[OCUPACION] INSTEAD OF DELETE
AS
DECLARE @p VARCHAR(50)
SELECT @p=Nombre FROM deleted

IF (SELECT Nombre FROM deleted)='Agente' OR (SELECT Nombre FROM deleted)='Constructor' OR  (SELECT Nombre FROM deleted)='Doctor' OR  (SELECT Nombre FROM deleted)='Ingeniero'
BEGIN
 RAISERROR('NO SE PUEDE ELIMINAR AL SER UN VALOR DEFAULT',16,-1)
    ROLLBACK TRANSACTION
END
ELSE
	 DELETE FROM OCUPACION
	 WHERE OCUPACION.Nombre=@p

GO
CREATE TRIGGER No_Borrar_TipoAnuncio ON [dbo].[TIPO_ANUNCIO] INSTEAD OF DELETE
AS
DECLARE @p VARCHAR(50)
SELECT @p=Nombre FROM deleted

IF (SELECT Nombre FROM deleted)='Destacado' OR (SELECT Nombre FROM deleted)='Normal' OR  (SELECT Nombre FROM deleted)='Oro' OR  (SELECT Nombre FROM deleted)='Platino'
BEGIN
 RAISERROR('NO SE PUEDE ELIMINAR AL SER UN VALOR DEFAULT',16,-1)
    ROLLBACK TRANSACTION
END
ELSE
	 DELETE FROM TIPO_ANUNCIO
	 WHERE TIPO_ANUNCIO.Nombre=@p

GO
CREATE TRIGGER No_Borrar_TipoPiso ON [dbo].[TIPO_PISO] INSTEAD OF DELETE
AS
DECLARE @p VARCHAR(50)
SELECT @p=Nombre FROM deleted

IF (SELECT Nombre FROM deleted)='Ceramica' OR (SELECT Nombre FROM deleted)='Concreto lujado' OR  (SELECT Nombre FROM deleted)='Porcelanato'
BEGIN
 RAISERROR('NO SE PUEDE ELIMINAR AL SER UN VALOR DEFAULT',16,-1)
    ROLLBACK TRANSACTION
END
ELSE
	 DELETE FROM TIPO_PISO
	 WHERE TIPO_PISO.Nombre=@p


GO
CREATE TRIGGER No_Borrar_TipoInmueble ON [dbo].[TIPO_INMUEBLE] INSTEAD OF DELETE
AS
DECLARE @p VARCHAR(50)
SELECT @p=Nombre FROM deleted

IF (SELECT Nombre FROM deleted)='Apartamento' OR (SELECT Nombre FROM deleted)='Casa' OR  (SELECT Nombre FROM deleted)='Lote'
BEGIN
 RAISERROR('NO SE PUEDE ELIMINAR AL SER UN VALOR DEFAULT',16,-1)
    ROLLBACK TRANSACTION
END
ELSE
	 DELETE FROM TIPO_INMUEBLE
	 WHERE TIPO_INMUEBLE.Nombre=@p
	 



